name: water

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  bot:
    steps:
      - name: 'send drink water message'
        run: bash ./water.sh
        with:
          WATERURL: ${{ secrets.WATERURL }}
